LEAGUE_CONFIG = {'E0': 'Barclays Premier League',
                 'E1': 'English League Championship',
                 'F1': 'French Ligue 1',
                 'D1': 'German Bundesliga',
                 'D2': 'German 2. Bundesliga',
                 'I1': 'Italy Serie A',
                 'I2': 'Italy Serie B',
                 'USA1': 'Major League Soccer',
                 'USA2': 'United Soccer League',
                 'SP1': 'Spanish Primera Division',
                 'P1': 'Portuguese Liga',
                 'N1': 'Dutch Eredivisie',
                 'B1': 'Brasileiro Série A',
                 'C1': 'Chinese Super League',
                 'AG1': 'Argentina Primera Division',
                 'AU1': 'Australian A-League'}